### ISSUE TITLE
Add tracking to custom links

### ISSUE THREAD

**Issue by dhannad** [ITS-UofIowa/uiowa_bar#19]
onclick="ga(‘send’, ‘event’, ‘UI bar’, ‘Click’, ‘%linktitle’);" 

Add the above code to the custom LINK, replacing %linktitle with the text from the LINK's title field.

**Comment by genjohnson** [comment]
Copied to the uiowa_bar repo in the uiowa organization - https://github.com/uiowa/uiowa_bar/issues/9, since that's the repo we're using in the SiteNow install profiles.
